refactor(root): modified code preview component
mi6/ic-design-system pull request #1022
Opened 2024-06-25 10:11 UTC by gd2910

## Summary of the changes
moved code action buttons from bottom of code preview and rearranged to match design on ticket

## Related issue
#938 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-06-26 07:34 UTC, GCHQ-Developer-530 approved these changes

2024-06-26 08:00 UTC, GCHQ-Developer-299 requested changes
<img width="387" alt="Screenshot 2024-06-26 at 08 57 37" src="https://github.com/mi6/ic-design-system/assets/111292477/e4514276-9a0c-4f6c-b3b7-db9ec15f65b4">

The snippet-container currently inherits a border-top from '.link-zone' that gives it a double-thick border that I think looks a bit unattractive. Could you remove that border for the snippet container please? (but make sure the link-zone above still has it)
<img width="354" alt="Screenshot 2024-06-26 at 08 59 29" src="https://github.com/mi6/ic-design-system/assets/111292477/8872c91c-060c-4089-a61a-ce5bd573e613">

2024-06-26 08:22 UTC, GCHQ-Developer-094 commented
Happy from design perspective - agree double thick border to be fixed first.

2024-06-26 08:29 UTC, ad9242 commented
should there be a bit more top padding in the lower typescript/javascript bar? when focused, it obscures the selected tab indicator:

![image](https://github.com/mi6/ic-design-system/assets/116102637/cdc9e245-5aff-4599-8d46-4d29f7497636)

2024-06-26 15:41 UTC, GCHQ-Developer-112 requested changes
<img width="322" alt="Screenshot 2024-06-26 at 16 39 55" src="https://github.com/mi6/ic-design-system/assets/113986285/02b80419-41c3-4ab2-a2b5-9222369dd049">

This design doesn't work on smaller devices. The screenshot shows a width of 375px

2024-06-26 15:48 UTC, ad9242 commented
found another issue:
if you have a small window size you initially get the big buttons
![image](https://github.com/mi6/ic-design-system/assets/116102637/42779c72-d1d2-4cb3-85ec-81f5b12247c6)

but when you make the window slightly bigger, they change to the small buttons:

2024-07-04 06:57 UTC, GCHQ-Developer-530 approved these changes

2024-07-04 11:48 UTC, GCHQ-Developer-299 approved these changes

2024-07-04 12:02 UTC, GCHQ-Developer-112 approved these changes

2024-07-04 12:04 UTC, merged