ci(root): update deployment workflow to incorporate v3 branch
mi6/ic-design-system pull request #1036
Opened 2024-07-03 12:20 UTC by GCHQ-Developer-530

## Summary of the changes
Update deployment workflow to incorporate v3 branch, where v3 work is hosted separately to other branch work

## Related issue

Half of https://github.com/mi6/ic-ui-kit/issues/2059

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-07-08 15:13 UTC, GCHQ-Developer-847 submitted a review, later dismissed

2024-07-10 07:39 UTC, gd2910 submitted a review, later dismissed

2024-07-10 07:41 UTC, GCHQ-Developer-112 requested changes
Just found a potential issue

2024-07-10 07:46 UTC, GCHQ-Developer-112 approved these changes

2024-07-10 07:53 UTC, gd2910 approved these changes

2024-07-10 07:54 UTC, merged