docs(root): addressed various punctuation
mi6/ic-design-system pull request #1099
Opened 2024-08-23 14:35 UTC by MI6-94

Addressed various punctuation

- [x ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-08-23 15:24 UTC, GCHQDeveloper823 requested changes
Please change the text in line 66 of the install-components.mdx file from "relased" to "released"

2024-08-23 15:24 UTC, GCHQDeveloper823 commented on src/content/structured/get-started/install-components.mdx
Line 66 needs updating from "relased" to "released"

2024-08-27 08:01 UTC, MI6-286 commented on src/content/structured/get-started/angular.mdx
> +Or for standalone components, import the `CUSTOM_ELEMENTS_SCHEMA` into the `.ts` file of any component using the components on this Design System.
Think it should be "from this Design System" instead of "on this Design System" here.

2024-08-27 08:13 UTC, MI6-286 commented on src/content/structured/components/section-container/guidance.mdx
> +Section containers are used in other components to control alignment of their content. The following components use section containers with the specified alignments.
Either keep ICDS here or if removing it, don't add 'other' so that it reads "Section containers are used in components to control...".

2024-08-29 10:00 UTC, MI6-94 commented
Complete work for #919 .

2024-08-29 10:46 UTC, GCHQ-Developer-299 commented on src/content/structured/accessibility/requirement/meeting-the-policy.mdx
> +    href="https://www.rnib.org.uk/nb-online/rise-depression-rates-people-sight-loss"
I think this link has been incorrectly replaced

2024-08-30 10:48 UTC, MI6-286 approved these changes

2024-08-30 10:52 UTC, GCHQ-Developer-299 approved these changes

2024-08-30 11:06 UTC, merged