Bugfix/1052 ic select code preview mismatch
mi6/ic-design-system pull request #1107
Opened 2024-09-05 09:43 UTC by lz405

## Summary of the changes

Edited the code snippets to match the preview

## Related issue

Issue #1052 

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-09-05 09:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-design-system?pullRequest=1107) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-design-system?pullRequest=1107) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-design-system?pullRequest=1107) it.</sub>

2024-09-05 12:49 UTC, GCHQ-Developer-530 requested changes
Please can you squash your commits into one? Looks good to me other than that!

2024-09-06 08:29 UTC, GCHQ-Developer-530 approved these changes

2024-09-06 09:34 UTC, GCHQ-Developer-299 approved these changes

2024-09-06 09:34 UTC, merged