docs(root): add guidance for neutral alert and show default icon prop
mi6/ic-design-system pull request #1171
Opened 2024-10-17 12:29 UTC by lz405

## Summary of the changes

Add guidance for neutral alert and show default icon prop.

## Related issue

Issue #1126 

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-10-17 14:50 UTC, ad9242 requested changes

2024-10-17 14:50 UTC, ad9242 commented on src/content/structured/components/alerts/code.mdx
> +  show-default-icon="true"
```suggestion
  show-default-icon="false"
```
should this be "false"? It doesn't seem right to set it to true but then supply a custom SVG to use

2024-10-21 08:37 UTC, MI6-286 approved these changes

2024-10-28 12:00 UTC, GCHQ-Developer-847 approved these changes
Noticed the issue with the margin when `showDefaultIcon` is false but I know it will be fixed by [PR #2616](https://github.com/mi6/ic-ui-kit/pull/2616) so have approved :)

2024-11-07 12:09 UTC, gd2910 approved these changes

2024-11-07 12:16 UTC, merged