1158 add designing for accessibility tips
mi6/ic-design-system pull request #1172
Opened 2024-10-17 15:32 UTC by mi6-378

## Summary of the changes

I have made changes within the accessibility needs section of the website. I have created visual designs and suggestions to show people what is deemed as good accessibility versus bad accessibility.

I explored neurodiversity, invisible illnesses, motor needs, visual needs and auditory needs.

2024-10-17 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-design-system?pullRequest=1172) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-design-system?pullRequest=1172) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-design-system?pullRequest=1172) it.</sub>

2024-10-18 10:02 UTC, MI6-286 commented on src/content/structured/accessibility/needs/general.mdx
> +  has designed effective accessibility posters from which the accessibility
Suggestion to change this sentence to - "The Home Office has created effective posters on designing for accessibility from which the accessibility needs section has taken inspiration" - and change the link text to be 'posters on designing for accessibility'. This link text better describes where the link is taking you.

2024-10-18 10:20 UTC, MI6-286 commented on src/content/structured/accessibility/needs/general.mdx
> +Writing in a large font size will put less writing on a page and make the words more readable.
It might be good to suggest font sizes that are generally considered accessible.

2024-10-18 10:26 UTC, MI6-286 commented on src/content/structured/accessibility/needs/invisible.mdx
> +    caption="An error message that blames the person rather than telling them how to fix it."
Suggest the caption should be changed to something like "Error messages should not blame the person or fail to tell them how to fix the issue."

2024-10-18 10:28 UTC, MI6-286 commented on src/content/structured/accessibility/needs/invisible.mdx
> +Pop-ups and toasts need to ensure they are visible for a good amount of time, and they don’t flash up too quickly on the screen.
Suggested change - "Make sure pop-ups and toasts are visible for a good amount of time, and that they don't flash up too quickly on the screen".

2024-10-18 10:30 UTC, MI6-286 commented on src/content/structured/accessibility/needs/motor.mdx
> +    caption="The cursors show a larger clickable area that includes the text for the buttons."
Not sure on wording, change to something like "The cursors are positioned on a larger clickable area that includes the text for the button."

2024-10-18 10:30 UTC, MI6-286 commented on src/content/structured/accessibility/needs/motor.mdx
> +    caption="The cursors show the smaller clickable areas, which make it harder for people with motor needs."
Same as above comment.

2024-10-18 10:31 UTC, MI6-286 commented on src/content/structured/accessibility/needs/neurodiversity.mdx
> +Where possible, use [simple words](/styles/content-style/voice-and-tone) no harder than a reading age of 9.
Suggested change - "Where possible, use simple words and aim for a maximum reading age of 9."

2024-10-18 10:35 UTC, MI6-286 commented on src/content/structured/accessibility/needs/invisible.mdx
> +Ensure any error messages explain what needs to be done to fix the error.
Our guidance states not to use ensure, so best to follow it and change to 'Make sure'.

2024-10-18 10:37 UTC, MI6-286 commented on src/content/structured/accessibility/needs/neurodiversity.mdx
> +  Please ensure that any text in the diagram is accessible with a screen reader."
Change 'ensure' to 'make sure'.

2024-10-21 09:57 UTC, MI6-286 commented on src/content/structured/accessibility/needs/neurodiversity.mdx
> +Where possible, use [simple words](/styles/content-style/voice-and-tone) and aim for a maximum reading ager of 9.
Typo (age instead of ager).

2024-10-21 10:16 UTC, MI6-286 approved these changes

2024-10-21 10:41 UTC, MI6-286 approved these changes

2024-10-21 11:01 UTC, GCHQ-Developer-299 approved these changes

2024-10-21 11:02 UTC, GCHQ-Developer-530 requested changes
Please squash all commits into one

2024-10-21 11:30 UTC, GCHQ-Developer-530 approved these changes

2024-10-21 12:12 UTC, merged