1020 update landing pages for developers and designers getting started new
mi6/ic-design-system pull request #1209
Opened 2024-11-18 11:58 UTC by mi6-378

## Summary of the changes

I have updated the Getting Started Pages, including adding cards and updating the 'Why we built a design system' page. I imported in the tree view branch and altered the nav priority of each page.

## Checklist

- [X] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-11-19 14:15 UTC, GCHQ-Developer-112 commented
View your branch deployment here: https://mi6.github.io/ic-design-system-githubpages/branches/1020-update-landing-pages-for-developers-and-designers-getting-started-new

2024-11-21 07:48 UTC, GCHQ-Developer-530 requested changes
Can you update the links on the homepage to go to the design and development pages now that they exist? Should just be the href for 'Explore design' and the href for 'Explore development'

2024-11-21 13:35 UTC, GCHQ-Developer-112 commented on src/config.js
>      develop: {
There are empty hrefs in this object. Was this intentional?

2024-11-21 13:38 UTC, GCHQ-Developer-112 commented on src/content/structured/get-started/index.mdx
> +We are expanding the UI Kit. You can check out the [roadmap](/community/roadmap) for what's coming. If you would like to help, please [read more on how to contribute.](/community)
```suggestion
We are expanding the UI Kit. You can check out the [roadmap](/community/roadmap) for what's coming. If you would like to help, please read more on [how to contribute.](/community)
```

2024-11-22 10:01 UTC, closed without merging