docs(root): updated Get Started pages
mi6/ic-design-system pull request #1218
Opened 2024-11-22 09:48 UTC by mi6-378

Prettier run, nav priority altered, Overview pages created

## Summary of the changes

Created new PR linking to old one here: #1209

2024-11-22 11:01 UTC, GCHQ-Developer-530 requested changes
Looking good - just one thing I noticed across all the get started pages is that the cards aren't responsive to smaller screen sizes (they're causing horizontal scroll).

Could you update the cards to be displaying in a column if they're on a small screen?

<img width="331" alt="Screenshot 2024-11-22 at 10 59 30" src="https://github.com/user-attachments/assets/6aaa8d2a-4a29-488f-ab30-4245497bdae2">

2024-11-25 14:19 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2024-11-26 11:10 UTC, GCHQ-Developer-112 commented on src/content/structured/get-started/images/designing-for-accessibility.svg
Please get rid of duplicate images, ideally keep the 2x sized images and get ride of the smaller ones

2024-11-27 10:10 UTC, GCHQ-Developer-112 reviewed
There's inconsistency with how the horizontal cards look on mobile (375px). To avoid truncation, there should be a small viewport size chosen where no image is shown
<img width="365" alt="Screenshot 2024-11-26 at 11 13 34" src="https://github.com/user-attachments/assets/4159575c-5c18-4dd3-89e6-d368c3fa928f">

2024-12-02 14:48 UTC, GCHQ-Developer-299 approved these changes

2024-12-03 14:35 UTC, GCHQ-Developer-112 commented
One of the images is causing an x-overflow (horizontal scroll)
<img width="560" alt="Screenshot 2024-12-03 at 14 29 10" src="https://github.com/user-attachments/assets/5fb74e6c-0bf7-4c08-bb44-22e51a5e6454">

2024-12-09 07:34 UTC, GCHQ-Developer-530 approved these changes

2024-12-09 10:53 UTC, GCHQ-Developer-530 approved these changes

2024-12-09 11:14 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-12-09 14:20 UTC, GCHQ-Developer-299 commented on src/templates/Homepage/index.css
> -@media screen and (min-width: 769px) and (max-width: 992px) {
This 992px breakpoint shouldn't be changed, i don't think - it's based on our breakpoint css tokens
```css
  --ic-breakpoint-xs: 0;
  --ic-breakpoint-sm: 576px;
  --ic-breakpoint-md: 768px;
  --ic-breakpoint-lg: 992px;
  --ic-breakpoint-xl: 1200px;
```

2024-12-09 14:21 UTC, GCHQ-Developer-299 commented on src/templates/Homepage/index.css
> -@media screen and (min-width: 769px) and (max-width: 992px) {
if you need it to be bigger, maybe use 1200px?

2024-12-10 09:59 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-12-10 10:22 UTC, GCHQ-Developer-530 commented on src/config.js
>        button: [
The href's further up in this file for the design section need updating as well

2024-12-10 10:32 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2024-12-10 10:34 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-12-10 10:44 UTC, GCHQ-Developer-299 approved these changes

2024-12-10 10:44 UTC, GCHQ-Developer-530 approved these changes

2024-12-10 10:48 UTC, merged