feat(root): adds dark mode switch
mi6/ic-design-system pull request #1222
Opened 2024-11-26 12:26 UTC by ad9242

## Summary of the changes
- Adds dark mode switch to site.
- Added system color preference. When a user first visits the page the initial theme will be whatever their system preference is
- Added theme persistance through sessionStorage. If a user wants to adjust the system preference, they press the button and their preference is stored in sessionStorage where it will be used as the user's preferred theme if they refresh the page.
- Added dark mode colors to guidance site specific elements. Tried to base them off the colors of the other components, however please comment if some don't seem correct :) #1133 

## Related issue
#1216

## Checklist
- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-11-26 14:48 UTC, GCHQ-Developer-299 approved these changes

2024-11-28 14:02 UTC, ad9242 commented
Suggestion to use local storage or a cookie rather than session storage. If you open a page in a new window, it reverts back to your OS setting

2024-12-02 12:59 UTC, gd2910 commented
At 90% page zoom, when hovering the button, I get a horizontal scroll appear. Only when going to light mode though. Small issue but overflow-x: hidden on the <body> fixes it if it is seen as an issue.

2024-12-03 08:58 UTC, GCHQ-Developer-530 requested changes
Found a couple of issues. The first time I open the site with dark mode as my system setting, it seems to know I'm in dark mode but doesn't update the site:
Cookie banner
<img width="1035" alt="Screenshot 2024-12-03 at 08 54 59" src="https://github.com/user-attachments/assets/7bf87509-cbef-4459-b85e-4ad729c084c7">

Site
<img width="1440" alt="Screenshot 2024-12-03 at 08 55 12" src="https://github.com/user-attachments/assets/43012ae4-550a-4c6b-9a9e-7b1bcd27da3b">

After I click the dark mode enabler button to light mode then dark mode again it's fixed itself and displays dark mode. 
When in dark mode, the bottom image on the homepage means that some of the text isn't readable, a new image might need generating for dark mode that has darker boxes.

<img width="1233" alt="Screenshot 2024-12-03 at 08 54 25" src="https://github.com/user-attachments/assets/c2c4810a-e76f-4b0a-ac1a-22f86b5d58c0">

2024-12-04 17:01 UTC, GCHQ-Developer-847 approved these changes

2024-12-05 07:19 UTC, GCHQ-Developer-530 approved these changes

2024-12-05 08:55 UTC, merged