feat(root): added link to v3 guidance site
mi6/ic-design-system pull request #1228
Opened 2024-11-28 13:27 UTC by GCHQ-Developer-741

## Summary of the changes
- Added banner and footer link to direct people to v3 guidance site

## Related issue
#1033 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-11-28 14:20 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2024-11-28 14:23 UTC, GCHQ-Developer-299 approved these changes

2024-11-28 14:46 UTC, gd2910 commented
A bit late reviewing, but would the action button in the ic-alert benefit from a tooltip or icon to show that it opens in a new page?

2024-11-28 15:31 UTC, gd2910 approved these changes

2024-11-29 09:10 UTC, GCHQ-Developer-299 requested changes
Blocking this from merging because we're going to wate until v3 is properly out

2024-12-05 14:18 UTC, MI6-255 commented
I actually think this should be tweaked slightly, depending on how we want to announce v3 going into it's pre-release:

1. Do we want to put this banner up as part of pre-release? If so, the language in this needs to change to say it's pre-release and be clear this isn't the stable version.
2. Do we want this banner to go up once it is fully stable? If so, this banner is potentially months off being released.

2024-12-05 14:18 UTC, MI6-255 requested changes
Requested change of language

2024-12-06 12:49 UTC, MI6-255 submitted a review, later dismissed

2025-03-04 15:50 UTC, ad9242 approved these changes

2025-03-04 16:02 UTC, merged