docs(root): added @next scope, updated instructions to latest
mi6/ic-design-system pull request #1296
Opened 2024-12-23 14:26 UTC by MI6-255

## Summary of the changes

docs(root): added @next scope, updated instructions to latest 

updated all sets of getting started to use the latest library versions, after testing with each

## Related issue

#1290

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-12-31 15:08 UTC, ad9242 reviewed
just one comment

2024-12-31 15:08 UTC, ad9242 commented on src/content/structured/get-started/vue.mdx
>            // treat all tags with a dash as custom elements
should this comment be changed to reference only "ic" elements rather than all custom elements?

2025-01-02 10:29 UTC, MI6-255 commented on src/content/structured/get-started/vue.mdx
>            // treat all tags with a dash as custom elements
Updated!

2025-01-02 13:46 UTC, GCHQ-Developer-847 requested changes

2025-01-02 13:46 UTC, GCHQ-Developer-847 commented on src/content/structured/get-started/vue.mdx
> +          // treat any tag that starts with ic- as custom elementss
```suggestion
          // treat any tag that starts with ic- as a custom element
```

2025-01-02 13:46 UTC, GCHQ-Developer-847 commented on src/content/structured/get-started/angular.mdx
> +### For Modules
I think this should be in sentence case - same for the other three headings that have been added
```suggestion
### For modules
```

2025-01-02 13:46 UTC, GCHQ-Developer-847 commented on src/content/structured/get-started/angular.mdx
> +Include CUSTOM_ELEMENTS_SCHEMA in the decorator object in the same file:
```suggestion
Include `CUSTOM_ELEMENTS_SCHEMA` in the decorator object in the same file:
```

2025-01-02 13:46 UTC, GCHQ-Developer-847 commented on src/content/structured/components/date-picker/code.mdx
>  ### Javascript dates
Tiny thing but may as well fix this at the same time?
```suggestion
### JavaScript dates
```

2025-01-06 10:02 UTC, GCHQ-Developer-847 requested changes

2025-01-06 10:52 UTC, GCHQ-Developer-847 approved these changes

2025-01-06 10:54 UTC, GCHQ-Developer-299 approved these changes

2025-01-06 10:55 UTC, merged