docs(root): added heading for componentdetails
mi6/ic-design-system pull request #138
Opened 2022-12-14 12:13 UTC by GCHQ-Developer-741

## Summary of the changes
After conversation with designers, instead of refactoring the codedetails tables to include the headers in the AnchorNav, added a Component Details header to markdown.

## Related issue
#25 

## Checklist
- [x] I have manually accessibility tested any changes, if relevant.

2022-12-14 13:54 UTC, GCHQ-Developer-530 approved these changes

2022-12-15 14:44 UTC, jd239 commented
On some pages we have <component-name> details and a generic 'component details' with this update. Feels like we should perhaps have <component-name> details so there is consistent headings on all the code pages.

2022-12-15 14:44 UTC, jd239 requested changes
Just the single comment. Happy to remove 'request changes' once agreement is made.

2022-12-15 15:32 UTC, ad9242 approved these changes

2022-12-15 16:12 UTC, merged