Gatsby documentation
mi6/ic-design-system pull request #239
Opened 2023-01-19 14:01 UTC by gd2910

## Summary of the changes

Documentation page created for using @ukic components in Gatsby.

To review changes please see 'Get Started -> Get Components -> Gatsby'

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-01-19 14:20 UTC, ad9242 requested changes

2023-01-19 14:20 UTC, ad9242 commented on src/content/structured/get-started/gatsby.mdx
> +You need to intstall an extra package to allow Gatsby to render the components server side.
```suggestion
Install the `gatsby-plugin-stencil` package to allow Gatsby to render the components server side.
```

2023-01-19 14:20 UTC, ad9242 commented on src/content/structured/get-started/gatsby.mdx
> +import "@ukic/web-components/dist/core/core.css";
```suggestion
import "@ukic/react/dist/core/core.css";
```

2023-01-20 11:36 UTC, jd239 requested changes
Looks good. Just a single comment :)

2023-01-20 11:36 UTC, jd239 commented on src/content/structured/get-started/gatsby.mdx
> +project / src / pages / index.jsx;
It's possible the developer is using the TS template for Gatsby perhaps say something 

`Add the following to the top level index file for your project` and remove the folder destination from the code example.

2023-01-20 13:41 UTC, gd2910 commented
Comments actioned and 'helpful links' edited to follow style and tone in the rest of the document

2023-01-23 15:15 UTC, ad9242 requested changes

2023-01-23 15:15 UTC, ad9242 commented on src/content/structured/get-started/gatsby.mdx
> +In your `gatsby-config.js` file (at the root of the project) add the following to the `module.exports`:
```suggestion
In your `gatsby-config.js` file (at the root of the project) add the following:
```
I don't think it needs the module.exports (I think that is something for Vue?)

2023-01-23 15:15 UTC, ad9242 commented on src/content/structured/get-started/gatsby.mdx
> +The Gatsby documentation contains more information on the [Stencil plugin](https://www.gatsbyjs.com/plugins/gatsby-plugin-stencil/) used, and further information can be found on [using Stencil in Gat
```suggestion
The Gatsby documentation contains more information on the [plugin used.](https://www.gatsbyjs.com/plugins/gatsby-plugin-stencil/) Further information can be found on [using Stencil in Gatsby](https://dev.to/brunnerlivio/use-stencil-with-gatsbyjs-1omo).
```

Currently reads to me like it is a Stencil plugin, so have tried to make it sound less like that

2023-01-24 13:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mi6/ic-design-system?pullRequest=239) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mi6/ic-design-system?pullRequest=239) before we can accept your contribution.<br/>**9** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: GCHQ-Developer-530<br/>:white_check_mark: GCHQ-Developer-741<br/>:white_check_mark: chrisns<br/>:white_check_mark: MI6-27<br/>:white_check_mark: gd2910<br/>:white_check_mark: ad9242<br/>:white_check_mark: jd239<br/>:white_check_mark: GCHQ-Developer-847<br/>:white_check_mark: GCHQDeveloper638<br/>:x: ASM995<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mi6/ic-design-system?pullRequest=239) it.</sub>

2023-01-24 14:23 UTC, ad9242 commented on src/content/structured/get-started/gatsby.mdx
> +The Gatsby documentation contains more information on the [plugin used.](https://www.gatsbyjs.com/plugins/gatsby-plugin-stencil/) Further information can be found on [using Stencil in Gatsby](https:/
```suggestion
The Gatsby documentation contains more information on the [plugin used.](https://www.gatsbyjs.com/plugins/gatsby-plugin-stencil/) Further information can be found on [using Stencil web components in Gatsby](https://dev.to/brunnerlivio/use-stencil-with-gatsbyjs-1omo).
```

2023-01-26 09:53 UTC, GCHQ-Developer-847 requested changes

2023-01-26 09:53 UTC, GCHQ-Developer-847 commented on src/content/structured/get-started/gatsby.mdx
> +Install the `gatsby-plugin-stencil` package to allow Gatsby to render the components server side.
```suggestion
Install the `gatsby-plugin-stencil` package to allow Gatsby to render the components server-side.
```

2023-01-26 14:08 UTC, jd239 commented
https://animated-fiesta-gvyom1k.pages.github.io/branches/215-add-documentation-on-how-to-use-components-in-gatsby/

2023-01-26 14:17 UTC, DBD324 requested changes
Added some comments on the page. Couple of small content style points.

2023-01-26 14:17 UTC, DBD324 commented on src/content/structured/get-started/gatsby.mdx
> +In the root of your project:
What is this suggesting? 'In the root write ...' or 'In the root find ...'. Need to add a verb to add context to the instruction.

2023-01-26 14:17 UTC, DBD324 commented on src/content/structured/get-started/gatsby.mdx
> +To get the correct styling with the ICDS components, import the core CSS file.
"To get the correct styling for the ICDS components, import the core CSS file."

2023-01-26 14:17 UTC, DBD324 commented on src/content/structured/get-started/gatsby.mdx
> +The Gatsby documentation contains more information on the [plugin used](https://www.gatsbyjs.com/plugins/gatsby-plugin-stencil/). Further information can be found on [using Stencil web components in
Link is non-dedscriptive. Describe the think you are linking to. 'Plugin used' is non descriptive and contextual. Instead use 'Gatsby StencilJS plug in' used.

2023-01-26 14:17 UTC, jd239 commented on src/content/structured/get-started/gatsby.mdx
> +The Gatsby documentation contains more information on the [plugin used](https://www.gatsbyjs.com/plugins/gatsby-plugin-stencil/). Further information can be found on [using Stencil web components in
```suggestion
The Gatsby documentation contains more information on [gatsby-plugin-stencil](https://www.gatsbyjs.com/plugins/gatsby-plugin-stencil/). Further information can be found on [using Stencil web components in Gatsby](https://dev.to/brunnerlivio/use-stencil-with-gatsbyjs-1omo).
```

2023-01-26 14:46 UTC, jd239 approved these changes

2023-01-26 16:24 UTC, ad9242 approved these changes

2023-01-26 16:50 UTC, merged