docs(root): restructure get started navigation to separate out testing
mi6/ic-design-system pull request #300
Opened 2023-02-16 13:28 UTC by GCHQ-Developer-530

## Summary of the changes

Restructure get started navigation to separate out testing with overview of the shadow dom moved out of jest page to overview.

## Related issue

#295

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-02-17 09:29 UTC, GCHQ-Developer-741 approved these changes

2023-02-17 14:48 UTC, MI6-255 submitted a review, later dismissed

2023-02-17 15:02 UTC, GCHQ-Developer-847 reviewed
Just noticed a couple of things - sorry, started reviewing before the second approval 😁

2023-02-17 15:06 UTC, GCHQ-Developer-847 requested changes
Just marked as 'changes requested' as I think my 'UI Kit' comment at least would need addressing - the other is subjective really

2023-02-20 11:47 UTC, GCHQ-Developer-847 submitted a review, later dismissed

2023-02-20 11:53 UTC, jd239 reviewed
Just an opinion but I feel the overview page should read slightly different. I think it would be good to have a short breakdown on:
- How we've built the components
- Why they include a Shadow DOM
- Testing components within Shadow DOM can be problematic because....
- Here are guides to testing our UI Kit components in different testing frameworks....(or something along those lines).

It's more of a we have created this section because....
Let me know your thoughts

2023-02-20 11:53 UTC, jd239 commented on src/content/structured/get-started/test-components.mdx
> +## Testing shadow components
```suggestion
## Testing the components
```

2023-02-20 13:48 UTC, jd239 commented on src/content/structured/get-started/test-components.mdx
> +At the core, our components are based off the web-components spec utilising the shadow DOM. With the shadow DOM, we can encapsulate each component’s markup structure, styling and behaviour so differe
```suggestion
At the core, UI Kit components are based off the web components specification, which utilises the shadow DOM. This makes it possible to encapsulate each component’s markup structure, styling and functionality.```

2023-02-20 14:48 UTC, MI6-255 approved these changes

2023-02-21 08:31 UTC, GCHQ-Developer-465 approved these changes

2023-02-21 08:36 UTC, merged