PX -> REM on guidance site
mi6/ic-design-system pull request #312
Opened 2023-02-21 17:36 UTC by gd2910

## Summary of the changes

PX values changed to REM excluding screen sizes, @media and 1px borders

## Related issue

#217 

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-02-22 11:27 UTC, GCHQ-Developer-465 requested changes
For consistency from previous work keep the rem value to 3 decimal places.

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/DoDontCaution/index.css
> +  margin-top: 0.1875rem;
Should this not be:
```suggestion
  margin-top: 0.188rem;
```
In previous work we have rounded to 3 decimal places.

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/DoDontCaution/index.css
> +  margin: 0 0 0.3125rem 0;
```suggestion
  margin: 0 0 0.313 rem 0;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/Layout/index.css
> +    transform: translate(-0.21875rem, var(--ic-space-xxxs));
```suggestion
    transform: translate(-0.219rem, var(--ic-space-xxxs));
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/Metadata/index.css
> +  margin-left: 0.3125rem;
```suggestion
  margin-left: 0.313rem;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/SubsectionNav/index.css
> +  box-shadow: 0 0 0 0.125rem #1759bc, 0 0 0 0.3125rem rgb(23 89 188 / 52%) !important;
```suggestion
  box-shadow: 0 0 0 0.125rem #1759bc, 0 0 0 0.313rem rgb(23 89 188 / 52%) !important;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/SubsectionNav/index.css
> +  margin-right: 0.5625rem;
```suggestion
  margin-right: 0.563rem;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/SubsectionNav/index.css
> +    margin-left: 0.1875rem;
```suggestion
    margin-left: 0.188rem;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/SubsectionNav/index.css
> +    padding-left: calc(var(--ic-space-md) - 0.1875rem);
```suggestion
    padding-left: calc(var(--ic-space-md) - 0.188rem);
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/SubsectionNav/index.css
> +    margin-left: 0.6875rem;
```suggestion
    margin-left: 0.688rem;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/SubsectionNav/index.css
> +    margin-left: -0.1875rem;
```suggestion
    margin-left: -0.188rem;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/SubsectionNav/index.css
> +    left: -0.6875rem;
```suggestion
    left: -0.688rem;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/SubsectionNav/index.css
> +    padding-left: calc(var(--ic-space-xl) - 0.1875rem) !important;
```suggestion
    padding-left: calc(var(--ic-space-xl) - 0.188rem) !important;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/components/WrappedCode/index.css
> +  padding: 0 0.4375rem;
```suggestion
  padding: 0 0.438rem;
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/content/structured/styles/components/IconFinder/index.css
> +  box-shadow: 0 -1px 0.1875rem rgb(0 0 0 / 12%),
```suggestion
  box-shadow: 0 -1px 0.188rem rgb(0 0 0 / 12%),
```

2023-02-22 11:27 UTC, GCHQ-Developer-465 commented on src/content/structured/styles/components/IconFinder/index.css
> +    0 0.1875rem 1px rgb(0 0 0 / 15%), 0 0.1875rem 0.375rem rgb(0 0 0 / 11%);
```suggestion
    0 0.188rem 1px rgb(0 0 0 / 15%), 0 0.188rem 0.375rem rgb(0 0 0 / 11%);
```

2023-02-22 12:25 UTC, GCHQ-Developer-465 submitted a review, later dismissed
This looks great now 👍

2023-02-22 12:29 UTC, MI6-255 requested changes
Looks like this one has a different commit message, but looks good other than that

2023-02-28 11:09 UTC, GCHQ-Developer-530 approved these changes

2023-03-01 16:41 UTC, GCHQ-Developer-465 approved these changes

2023-03-07 10:38 UTC, GCHQ-Developer-465 approved these changes

2023-03-08 15:19 UTC, MI6-255 approved these changes

2023-03-08 16:16 UTC, merged