Add z-index tokens and guidance to elevation page
mi6/ic-design-system pull request #347
Opened 2023-03-16 11:19 UTC by MI6-451

## Summary of the changes

Adds the z-index tokens and descriptions of use to the elevation page.

## Related issue

#313 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-03-16 12:46 UTC, GCHQ-Developer-530 approved these changes

2023-03-17 15:55 UTC, jd239 commented on src/content/structured/styles/elevation.mdx
Can we have the token in `monospace` to keep it consistent with the colours page?

2023-03-17 16:02 UTC, jd239 requested changes
Teeny weeny comments.

2023-03-17 16:02 UTC, jd239 commented on src/content/structured/styles/elevation.mdx
Can we also update the font on the shadows table as well please?

2023-03-22 07:50 UTC, GCHQ-Developer-530 approved these changes

2023-03-28 07:48 UTC, merged