feat: added to guidance page and improved code snippet examples to sh…
mi6/ic-design-system pull request #364
Opened 2023-03-24 15:09 UTC by za2201

## Summary of the changes

Added usage of tooltip to clarify what a tooltip is on the guidance page. 
Added component examples to code based on user  feedback confusion regarding placement of elements. Included the buttons in code examples already given and created an example with a chip.

## Related issue

#333 

## Checklist

- [y] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [y] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-03-28 09:05 UTC, GCHQ-Developer-741 approved these changes

2023-03-30 12:57 UTC, MI6-255 commented
Will need to rebase this PR off develop, let us know if you need a hand

2023-04-04 08:38 UTC, GCHQ-Developer-530 approved these changes

2023-04-04 14:37 UTC, jd239 approved these changes

2023-04-04 14:40 UTC, jd239 requested changes
Just a single comment.

2023-04-04 14:40 UTC, jd239 commented on src/content/structured/components/tooltips/code.mdx
> +</IcTooltip>`,
There is no closing `</IcChip>`

2023-04-04 14:43 UTC, jd239 requested changes

2023-04-04 14:43 UTC, jd239 commented on src/content/structured/components/tooltips/code.mdx
> +  <ic-button id="text-button"> Top </ic-button>
Can we give the buttons unique IDs please. Perhaps add an index number at the end `text-button-0` and remove the white-spaces around the button labels. I don't think they are required.

2023-04-05 14:21 UTC, jd239 commented on src/content/structured/components/tooltips/code.mdx
> +<IcTooltip target="text-button" label="This is a description of the button"  placement="bottom">
```suggestion
<IcTooltip target="text-button" label="This is a description of the button" placement="bottom">
```

2023-04-05 14:24 UTC, jd239 commented on src/content/structured/components/tooltips/code.mdx
> +    <svg slot="icon" width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
Can this be updated to use `<SlottedSVG slot="icon" width="20" height="20" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">`.
The reason for this is if a developer copies this snippet into a typescript project, the `slot` attribute on the SVG tag will display an error. Thanks

2023-04-24 14:57 UTC, MI6-451 approved these changes

2023-04-25 08:28 UTC, GCHQ-Developer-530 approved these changes

2023-05-02 07:47 UTC, jd239 approved these changes

2023-05-02 07:47 UTC, merged