fix: updated status tag components to chip in page header itself and …
mi6/ic-design-system pull request #365
Opened 2023-03-27 11:04 UTC by za2201

## Summary of the changes

Updated the header component tsx to display chip instead of status tag
Updated page header component page codes in guidance and code mdx files to display chip instead of status tag

## Related issue

#316 

## Checklist

- [y] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [y] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-03-29 14:19 UTC, ad9242 commented on src/content/structured/components/page-header/code.mdx
> +  <ic-chip slot="heading-adornment" label="Beta"></ic-chip>
```suggestion
  <ic-chip slot="heading-adornment" label="BETA", size="large"></ic-chip>
```
Wherever there is a chip , can we make it use the label "BETA" (uppercase) and use the "large" sized chip

2023-03-29 14:20 UTC, ad9242 requested changes
comment about using size="large" for chips and label="BETA"

2023-04-05 14:11 UTC, jd239 requested changes
Thanks for working on this ticket. Looks like a rogue `,` is mixed within the code snippets. Once that has been removed, happy to approve.

2023-04-05 14:11 UTC, jd239 commented on src/content/structured/components/page-header/code.mdx
> +  <IcChip slot="heading-adornment" label="BETA", size="large" />
```suggestion
  <IcChip slot="heading-adornment" label="BETA" size="large" />
```

2023-04-05 14:11 UTC, jd239 commented on src/content/structured/components/page-header/code.mdx
> +  <ic-chip slot="heading-adornment" label="BETA", size="large"></ic-chip>
```suggestion
  <ic-chip slot="heading-adornment" label="BETA" size="large"></ic-chip>
```

2023-04-05 14:11 UTC, jd239 commented on src/content/structured/components/page-header/code.mdx
> +  <IcChip slot="heading-adornment" label="BETA", size="large" />
```suggestion
  <IcChip slot="heading-adornment" label="BETA" size="large" />
```

2023-04-05 14:17 UTC, ad9242 commented on src/content/structured/components/page-header/code.mdx
> +  <IcChip slot="heading-adornment" label="BETA", size="large" />
oops, sorry - that was me

2023-04-17 09:35 UTC, GCHQ-Developer-112 commented
Hey @za2201 , please can rebase your branch off develop

2023-04-17 11:14 UTC, za2201 commented
Hi, rebase has been done

2023-04-17 13:40 UTC, MI6-451 submitted a review, later dismissed

2023-04-18 10:07 UTC, ad9242 commented
I think there are just 2 rogue `"label="BETA", ` (i.e. with commas that need to be removed)

2023-04-18 13:27 UTC, za2201 commented
requested changes made :)

2023-04-19 07:04 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2023-04-19 08:43 UTC, GCHQ-Developer-112 approved these changes

2023-04-19 08:57 UTC, GCHQ-Developer-112 requested changes
Hi @za2201, please can you amend your commits so they're more reflective of the work you've completed

2023-04-19 11:08 UTC, za2201 commented
Hi, I've done this I think

2023-04-19 11:09 UTC, za2201 commented
> Hi @za2201, please can you amend your commits so they're more reflective of the work you've completed

Hi, I've done this I think

2023-04-19 14:55 UTC, GCHQ-Developer-530 approved these changes

2023-04-24 16:20 UTC, MI6-451 submitted a review, later dismissed

2023-04-25 07:47 UTC, GCHQ-Developer-112 submitted a review, later dismissed

2023-04-25 13:33 UTC, gd2910 approved these changes

2023-05-11 11:21 UTC, MI6-255 submitted a review, later dismissed

2023-05-11 12:28 UTC, GCHQ-Developer-741 approved these changes

2023-05-11 12:48 UTC, GCHQ-Developer-847 submitted a review, later dismissed

2023-05-11 12:53 UTC, ad9242 submitted a review, later dismissed

2023-05-19 14:12 UTC, gd2910 commented
Please see https://github.com/mi6/ic-design-system/pull/473

2023-05-19 14:12 UTC, closed without merging