docs(root): add nested tabs code example
mi6/ic-design-system pull request #428
Opened 2023-04-20 14:45 UTC by GCHQ-Developer-530

## Summary of the changes

Add nested tabs code example. You'll need to run npm pack for web-components and react on develop in the ui kit and install those locally to see the example working.

## Related issue

#423 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-04-21 15:17 UTC, jd239 submitted a review, later dismissed

2023-04-25 09:12 UTC, MI6-255 requested changes
Looks good, only thing I'd suggest, with the tabs being centered and the nested tab being larger than the others, I wonder if we put a min width on it's container so it doesn't jump around the place as we move tabs? No need for this on code examples as this is just specific to our site

2023-04-25 09:34 UTC, GCHQ-Developer-530 commented
> Looks good, only thing I'd suggest, with the tabs being centered and the nested tab being larger than the others, I wonder if we put a min width on it's container so it doesn't jump around the place as we move tabs? No need for this on code examples as this is just specific to our site

I've updated the example to have a bigger outer tab than the nested tab so that the jumping doesn't happen 😊

2023-05-03 11:22 UTC, MI6-255 approved these changes

2023-05-03 13:59 UTC, GCHQ-Developer-112 approved these changes

2023-05-03 14:03 UTC, merged