docs(root): add guidance and code examples for min and max props
mi6/ic-design-system pull request #430
Opened 2023-04-21 11:10 UTC by GCHQ-Developer-530

## Summary of the changes

Add guidance and code examples for min and max props on text field. You'll need to run npm pack for web-components, react, and docs on 503-ictextfield-should-pass-all-other-props-available-to-input-components-and-check-for-other-components in the ui kit and install those locally to see the example working.

## Related issue

#427

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-04-24 12:38 UTC, DBD324 requested changes
A couple of specific changes requested on the edits in this file. There are a few other additions to the guidance that we would need to make that talks about how to add the min and max values, as well as how to change the text field to allow numeric input (as well as other allowable input types such as password)

2023-04-24 12:38 UTC, DBD324 commented on src/content/structured/components/text-input/guidance.mdx
> +When using min or max props, ensure to add visual indication of these values in the label or helper text.
"When setting minimum and maximum values using the `min` and `max` props, make sure to add an indication of these formatting rules in the helper text."

2023-04-24 12:38 UTC, DBD324 commented on src/content/structured/components/text-input/guidance.mdx
> +When using min or max props, ensure to add visual indication of these values in the label or helper text.
This is actually better palced in the next section for 'helper text'.

2023-04-24 12:38 UTC, DBD324 commented on src/content/structured/components/text-input/guidance.mdx
>  Use helper text in addition to the field label when additional information helps users understand what information is required.
This should appear below the image.

2023-04-24 12:38 UTC, DBD324 commented on src/content/structured/components/text-input/code.mdx
> +In this example, the error message will change for inputted values below min and above max.
In this example, an error message will display when the input is either below the `min` value or above the `max` value. This only effects numeric input fields.

2023-04-25 10:52 UTC, DBD324 requested changes

2023-04-25 10:52 UTC, DBD324 commented on src/content/structured/components/text-input/guidance.mdx
> +When setting min and max values using the min and max props, make sure to add an indication of these formatting rules in the helper text.
"When setting minimum and maximum values..." and can we use the code styling for 'min' and 'max' props?

2023-04-25 10:52 UTC, DBD324 commented on src/content/structured/components/text-input/code.mdx
> +### With min and max
"With min and max values"

2023-04-26 08:42 UTC, DBD324 submitted a review, later dismissed

2023-05-03 11:26 UTC, MI6-255 requested changes

2023-05-03 11:26 UTC, MI6-255 commented on src/content/structured/components/text-input/code.mdx
> +  validationText="now it has really gone to (coffee) pot"
I think these validations don't show what we want them to with min/max, I think it'd be more setting the value to say 6 (over the max value) and showing that validation?

2023-05-03 12:12 UTC, MI6-255 requested changes

2023-05-03 12:12 UTC, MI6-255 commented on src/content/structured/components/text-input/code.mdx
> +  validationText="now it has really gone to (coffee) pot"
I think only the web component was updated here. But also, unless I'm getting the wrong end of the stick, I think the validation needs to just be removed? If you have the value set to 6 in this example, the validation is automatically generated. Which I think is what we want to display here?

2023-05-03 14:05 UTC, DBD324 approved these changes
Changes look good. Thank you

2023-05-03 14:12 UTC, merged