fix: updated and fixed small typos on code examples
mi6/ic-design-system pull request #432
Opened 2023-04-21 16:50 UTC by c347347

## Summary of the changes

Corrected small typos in code examples stated on issue #252 and following small changes were made:

- In the react example of breadcrumbs, the second breadcrumb href has an extra space, removed extra spaces to fix the issue

- Skeleton contains height="20" but height doesn't exist, removed height from react example IcSkeleton

- Textfield example comes with maxLength="25" but a string isn't assignable to a number so it would only accept maxLength={25} - changed maxLength="25" to {25}

- The Select react example has const [value, setValue] = useState(null); however in typescript projects where is needed, null causes errors. Updated typescript code with: const [value, setValue] = useState("");

- The prop rows on the react component IcTextField is a number type. The react examples with the prop rows should be in brackets instead of speech marks

(There was an issue with the previous PR for this issue, all the changes were lost after rebasing, however it is updated and typos fixed ready to be merged if there are no other issues)

## Related issue

#252

## Checklist

- [Y] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [Y] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-04-24 06:27 UTC, GCHQ-Developer-530 approved these changes

2023-04-24 08:42 UTC, GCHQ-Developer-112 requested changes
Hey @c347347, thank you for your contribution!

Please could you amend your commit message so it includes the scope. More information on how to structure your commit and what scope to use can be found in our [`ic-design-system` CONTRIBUTING.md](https://github.com/mi6/ic-design-system/blob/main/CONTRIBUTING.md#git-commit)

2023-04-24 14:47 UTC, MI6-451 approved these changes

2023-04-27 14:30 UTC, GCHQ-Developer-530 approved these changes

2023-04-27 16:02 UTC, gd2910 approved these changes
Looks good :) thanks for your submission!

2023-05-03 13:59 UTC, GCHQ-Developer-112 approved these changes

2023-05-03 13:59 UTC, merged