543 classification banner on classification banner page overlays on footer content
mi6/ic-design-system pull request #440
Opened 2023-05-04 08:37 UTC by gd2910

## Summary of the changes

Removed ic-classification-banner that was causing issues in the guidance

## Related issue

#543
## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-05-10 09:04 UTC, GCHQ-Developer-530 submitted a review, later dismissed

2023-05-10 11:57 UTC, ad9242 requested changes
Can we also remove from the code.mdx as same issue occurs there?

2023-05-11 08:34 UTC, GCHQ-Developer-530 approved these changes

2023-05-11 08:58 UTC, ad9242 approved these changes

2023-05-11 08:59 UTC, merged