fix(root): fixed example of new tooltip method
mi6/ic-design-system pull request #469
Opened 2023-05-18 16:53 UTC by GCHQ-Developer-741

fixed example as the wrong tooltip was being targeted and therefore the method wasn't displaying in the preview

## Checklist
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-05-19 06:36 UTC, GCHQ-Developer-530 requested changes
Can you update the code snippets to show this change too?

2023-05-19 08:49 UTC, gd2910 submitted a review, later dismissed

2023-05-22 09:25 UTC, GCHQ-Developer-530 approved these changes

2023-05-22 15:30 UTC, MI6-451 approved these changes

2023-05-22 16:29 UTC, merged