docs(root): add code example for truncation in typography
mi6/ic-design-system pull request #471
Opened 2023-05-19 09:10 UTC by GCHQ-Developer-530

## Summary of the changes

Add code example for truncation in typography. Will need to pull down 345-add-see-more-truncation-pattern-for-typography in the ui kit to test locally as see more pattern hasn't been released yet.

## Related issue

#470

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-05-19 13:05 UTC, ad9242 requested changes

2023-05-19 13:05 UTC, ad9242 commented on src/content/structured/components/typography/code.mdx
> +    snippet: `<IcTypography max-lines="3" variant="body">
```suggestion
    snippet: `<IcTypography maxLines="3" variant="body">
```
camelCase for React

2023-05-19 13:05 UTC, ad9242 commented on src/content/structured/components/typography/code.mdx
> +  <IcTypography max-lines="3" variant="body">
```suggestion
  <IcTypography maxLines="3" variant="body">
```
and here

2023-05-22 12:56 UTC, ad9242 approved these changes

2023-05-23 11:14 UTC, MI6-451 approved these changes

2023-05-23 11:50 UTC, merged