Status tag chip fix
mi6/ic-design-system pull request #473
Opened 2023-05-19 14:04 UTC by gd2910

## Summary of the changes

New PR for https://github.com/mi6/ic-design-system/pull/365

## Related issue

#316 

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-05-22 06:49 UTC, GCHQ-Developer-530 approved these changes

2023-05-22 11:20 UTC, GCHQ-Developer-112 requested changes

2023-05-22 11:20 UTC, GCHQ-Developer-112 commented on src/components/Header/index.tsx
In this case, I think it makes sense to have a status tag because we are using it to show status. For example, our [patterns](https://design.sis.gov.uk/patterns) are still in development so a warning status tag is used. In the page header examples, we are using the status tag to display information so I think it makes sense for those to be chips instead.

2023-05-22 12:44 UTC, GCHQ-Developer-530 approved these changes

2023-05-23 13:52 UTC, GCHQ-Developer-112 approved these changes

2023-05-23 13:53 UTC, merged