fix(root): bug fix in pagination docs
mi6/ic-design-system pull request #489
Opened 2023-05-30 10:09 UTC by gd2910

## Summary of the changes

Bug fixes to pagination docs

## Related issue

#464 

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-05-30 12:32 UTC, GCHQ-Developer-112 approved these changes

2023-05-31 06:44 UTC, GCHQ-Developer-530 approved these changes

2023-05-31 14:43 UTC, GCHQ-Developer-847 requested changes

2023-05-31 14:43 UTC, GCHQ-Developer-847 commented on src/content/structured/components/pagination/guidance.mdx
> +  message="The carousel functionality is in development."
Should this be:
```suggestion
  message="The carousel pagination variant is in development."
```
based on the description in the ticket? https://github.com/mi6/ic-design-system/issues/464

2023-05-31 17:24 UTC, GCHQ-Developer-847 approved these changes

2023-06-02 14:27 UTC, merged