465 improve build times
mi6/ic-design-system pull request #508
Opened 2023-06-26 10:46 UTC by GCHQ-Developer-741

## Summary of the changes
Changes to graphql queries and plugins to try and improve gatsby build times

## Related issue
#465 

## Checklist
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-07-10 16:34 UTC, MI6-451 submitted a review, later dismissed

2023-07-13 10:12 UTC, GCHQ-Developer-847 requested changes
https://github.com/mi6/ic-design-system/pull/508#issuecomment-1633940901

2023-07-13 13:40 UTC, jd239 commented
When I click on the build and navigate through the site, the pages are coming up blank until I refresh the page.

I've also noticed the styling in the top navigation has gone funny:

![image](https://github.com/mi6/ic-design-system/assets/116016939/73b80976-4403-4bcf-8faa-e358ac5fb386)

2023-07-18 13:48 UTC, jd239 approved these changes

2023-07-18 14:46 UTC, GCHQ-Developer-847 approved these changes

2023-07-18 14:47 UTC, merged