258 review all external links and implement correct behaviour
mi6/ic-design-system pull request #526
Opened 2023-07-11 10:47 UTC by gd2910

## Summary of the changes

All IcLinks changed to reflect style rules regarding external links

## Related issue

#258

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-07-11 13:58 UTC, GCHQ-Developer-530 requested changes
Sorry this is going to be a massive faff 😭 but showIcon is a deprecated prop, so ic-link should show the external icon just by setting target to _blank. Please can you remove showIcon from each link? 😬

2023-07-14 12:34 UTC, GCHQ-Developer-530 reviewed
Looks really good - just one showIcon left to remove then happy to approve

2023-07-14 12:34 UTC, GCHQ-Developer-530 commented on src/components/ComponentDetails/SlotTable/index.tsx
> +            target="_blank"
```suggestion
            href="https://javascript.info/slots-composition"
            target="_blank"
```

2023-07-14 13:05 UTC, GCHQ-Developer-741 commented
> 

Should showIcon be removed from the code examples in the ic-link page?

2023-07-14 13:08 UTC, GCHQ-Developer-741 approved these changes

2023-07-14 13:09 UTC, GCHQ-Developer-530 approved these changes

2023-07-14 13:31 UTC, merged