docs(root): add empty state documentation
mi6/ic-design-system pull request #570
Opened 2023-08-09 11:06 UTC by GCHQ-Developer-530

## Summary of the changes

Add empty state documentation with code examples. To test this, the components will have to be built locally from the empty state component branch until https://github.com/mi6/ic-ui-kit/pull/982 is merged. 

## Related issue

 #487

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/accessibility.mdx
> +title: "Empty State"
```suggestion
title: "Empty state"
```

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/code.mdx
> +title: "Empty State"
```suggestion
title: "Empty state"
```

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/guidance.mdx
> +title: "Empty State"
```suggestion
title: "Empty state"
```

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/guidance.mdx
> +- No content yet exists due to the first-time use of the functionality,
```suggestion
- No content yet exists due to the first-time use of the functionality.
```

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/guidance.mdx
> +- Data was not successfully loaded,
```suggestion
- Data was not successfully loaded.
```

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/guidance.mdx
> +- A query or search term yielded no results,
```suggestion
- A query or search term yielded no results.
```

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/guidance.mdx
> +Use empty states to engage people and provide guidance on what is best to do next.
Remove? Repeat of above?

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/guidance.mdx
> +- [Alert](/components/alert)
```suggestion
- [Alert](/components/alert).
```

2023-08-30 08:28 UTC, MI6-94 commented on src/content/structured/components/empty-state/guidance.mdx
> +- [Loading indicator](/components/loading-indicator)
```suggestion
- [Loading indicator](/components/loading-indicator).
```

2023-08-30 12:11 UTC, DBD324 commented on src/content/structured/components/empty-state/guidance.mdx
> +Use empty states to engage people and provide guidance on what is best to do next.
Good catch

2023-08-30 14:53 UTC, DBD324 requested changes
A couple of changes requested. Need to wait for build before approval can be given. Need to see page to check sizing of imagery etc.

2023-08-30 14:53 UTC, DBD324 commented on src/content/structured/components/empty-state/guidance.mdx
> +## Introduction
Remove heading of introduction and replace with heading 'Component demo'

2023-08-30 14:53 UTC, DBD324 commented on src/content/structured/components/empty-state/guidance.mdx
> +An example of the empty state component.
remove as unnecessary

2023-08-31 13:16 UTC, DBD324 commented
When reviewing images noticed two required changes:
- Add warning status to the second image in the content section. 
- Reduce size of second image in when not to use section to a half width image. 

Otherwise looks good.

2023-08-31 13:26 UTC, DBD324 approved these changes
All comments have been actioned. Guidance is looking good to me.

2023-09-04 08:46 UTC, MI6-255 approved these changes

2023-09-04 08:47 UTC, MI6-255 commented
Approved, just need the build fixing

2023-09-05 06:32 UTC, merged