docs(root): adding docs for versioning and releases
mi6/ic-design-system pull request #65
Opened 2022-11-23 11:23 UTC by jd239

## Summary of the changes
New page within the guidance site detailing the teams approach to releases and versioning.

## Related issue
#20 

## Checklist
- [x] I have manually accessibility tested any changes, if relevant.

2022-11-23 12:04 UTC, GCHQ-Developer-530 commented on src/content/structured/get-started/releases-versioning.mdx
> +**Major releases** will contain breaking changes to the component libraries. Breaking changes will be communicated to the community as early as possible to allow teams to plan when to integrate the n
```suggestion
Major releases will be very infrequent with at least a year between major releases.
```

2022-11-23 12:05 UTC, GCHQ-Developer-530 commented on src/content/structured/get-started/releases-versioning.mdx
> +**Major releases** will contain breaking changes to the component libraries. Breaking changes will be communicated to the community as early as possible to allow teams to plan when to integrate the n
```suggestion
**Major releases** will contain breaking changes to the component libraries. Breaking changes will be communicated to the community as early as possible to allow teams to plan when to integrate the new packages into their projects. Major releases will be very infrequent with at least a year between major releases.
```

2022-11-23 16:58 UTC, ad9242 requested changes

2022-11-23 16:58 UTC, ad9242 commented on src/content/structured/get-started/releases-versioning.mdx
> +contribute: "https://github.com/mi6/ic-design-system/tree/main/src/content/structured/get-started/releases-versions.mdx"
should be releases-versioning.mdx

2022-11-23 17:02 UTC, ad9242 commented on src/content/structured/get-started/releases-versioning.mdx
> +contribute: "https://github.com/mi6/ic-design-system/tree/main/src/content/structured/get-started/releases-versions.mdx"
```suggestion
contribute: "https://github.com/mi6/ic-design-system/tree/main/src/content/structured/get-started/releases-versioning.mdx"
```

2022-11-23 17:14 UTC, GCHQ-Developer-112 commented on src/content/structured/get-started/releases-versioning.mdx
> +This page provides details on how the `@ukic/` packages will be released and versioned when published for Open Source.
```suggestion
This page provides details on how the `@ukic/` packages will be released and versioned when published for open source.
```

2022-11-23 17:14 UTC, GCHQ-Developer-112 commented on src/content/structured/get-started/releases-versioning.mdx
> +Releases will be triggered once the `Develop` branch pull request is merged into the `Main` branch. The package versions will follow the [semantic versioning](https://semver.org/) scheme.
```suggestion
Releases will be triggered once the `develop` branch pull request is merged into the `Main` branch. The package versions will follow the [semantic versioning](https://semver.org/) scheme.
```

2022-11-25 13:30 UTC, GCHQ-Developer-112 approved these changes

2022-11-25 14:11 UTC, ad9242 approved these changes

2022-11-25 14:12 UTC, merged