docs(root): roadmap update to latest version
mi6/ic-design-system pull request #706
Opened 2023-12-04 15:52 UTC by MI6-255

update the roadmap to reflect what we have worked on and working on

## Summary of the changes

Roadmap update to latest version

## Related issue

#661

2023-12-07 11:41 UTC, GCHQ-Developer-530 requested changes

2023-12-07 11:41 UTC, GCHQ-Developer-530 commented on src/content/structured/community/roadmap.mdx
> +- Releasing accordian.
I think the newly released components in this section should link to them e.g.
```suggestion
- Releasing [accordion](/components/accordion) component.
```

2023-12-13 18:41 UTC, GCHQ-Developer-112 requested changes

2023-12-13 18:41 UTC, GCHQ-Developer-112 commented on src/content/structured/community/roadmap.mdx
> +- Releasing dialog.
```suggestion
- [Dialog](https://design.sis.gov.uk/components/dialog) component.
```
In addition to the @GCHQ-Developer-530's suggested change, I don't think we need the word "releasing" before the component as these components have already been released. In the past, we have just stated the component

2023-12-18 08:25 UTC, GCHQ-Developer-530 approved these changes

2023-12-18 11:32 UTC, merged