docs(root): add canary component guidance
mi6/ic-design-system pull request #820
Opened 2024-02-15 14:59 UTC by GCHQ-Developer-530

## Summary of the changes

Add canary component guidance to versioning page

## Related issue

#729 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-02-15 17:22 UTC, GCHQ-Developer-847 requested changes

2024-02-15 17:22 UTC, GCHQ-Developer-847 commented on src/content/structured/get-started/releases-versioning.mdx
> +We consider a canary component acceptable for moving to Beta once customers have tested its usage and provided enough feedback suggesting they're happy with it.
```suggestion
We consider a canary component to be acceptable for moving to Beta once customers have tested its usage and provided enough feedback suggesting they're happy with it.
```

2024-02-15 17:22 UTC, GCHQ-Developer-847 commented on src/content/structured/get-started/releases-versioning.mdx
> +Canary components can be installed in the same way as normal `@ukic/` packages, but prefixed with canary e.g `@ukic/canary-react` or `@ukic/canary-web-components`. You can update to the latest canary
```suggestion
Canary components can be installed in the same way as normal `@ukic/` packages, but prefixed with canary, e.g. `@ukic/canary-react` or `@ukic/canary-web-components`. You can update to the latest canary version just as you would with normal `@ukic/` packages.
```

2024-02-15 17:22 UTC, GCHQ-Developer-847 commented on src/content/structured/get-started/releases-versioning.mdx
> +    Web components
```suggestion
    web components
```

2024-02-15 17:22 UTC, GCHQ-Developer-847 commented on src/content/structured/get-started/releases-versioning.mdx
> +  components guidance section of this site. Instead, docs can be viewed in our
Perhaps this should be capitalised as it is referring to the actual section on the site? I.e. which is alongside Styles etc.
```suggestion
  Components guidance section of this site. Instead, docs can be viewed in our
```

2024-02-16 08:59 UTC, GCHQ-Developer-299 approved these changes

2024-02-16 09:29 UTC, GCHQ-Developer-465 submitted a review, later dismissed

2024-02-19 09:19 UTC, GCHQ-Developer-847 approved these changes

2024-02-19 16:18 UTC, jd239 requested changes
Wondering if we change the language a bit so we specify the 'normal' @ukic packages as our core packages.

2024-02-19 16:18 UTC, jd239 commented on src/content/structured/get-started/releases-versioning.mdx
> +Canary components are unstable components in our versioning system that are released for testing purposes.
```suggestion
Canary components are unstable components that are released for testing purposes.
```

2024-02-19 16:18 UTC, jd239 commented on src/content/structured/get-started/releases-versioning.mdx
> +These components should not be used in production apps without understanding the risk that unexpected changes may be made to them, causing changes within the applications using them.
```suggestion
These components should not be used in production apps without understanding the risk that unexpected changes may be occur in order to fix bugs or improve functionality.
```

2024-02-19 16:18 UTC, jd239 commented on src/content/structured/get-started/releases-versioning.mdx
> +Canary components can be installed in the same way as normal `@ukic/` packages, but prefixed with canary, e.g. `@ukic/canary-react` or `@ukic/canary-web-components`. You can update to the latest cana
```suggestion
Canary components can be installed in the same way as normal `@ukic/` packages, but prefixed with canary, e.g. `@ukic/canary-react` or `@ukic/canary-web-components`. 
```

Wondering if the last sentence can be removed and add the command just like it's done on the 'Get the components' pages, so something like ....

```
// Canary Web Components
npm i @ukic/canary-web-components @ukic/fonts

// Canary React
npm i @ukic/canary-react @ukic/fonts
```

2024-02-20 08:51 UTC, GCHQ-Developer-299 approved these changes

2024-02-20 08:53 UTC, jd239 commented on src/content/structured/get-started/releases-versioning.mdx
> +These components should not be used in production apps without understanding the risk that unexpected changes may be occur in order to fix bugs or improve functionality.
```suggestion
These components should not be used in production apps without understanding the risk that unexpected changes may occur in order to fix bugs or improve functionality.
```

2024-02-20 10:08 UTC, merged