feat(root): add code examples for page header using slots
mi6/ic-design-system pull request #839
Opened 2024-02-27 21:24 UTC by zxh722

## Summary of the changes

Code example added in for changing slots within the page header, changing the typography of a page header semantically.

## Related issue

#632 

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-02-28 10:07 UTC, GCHQ-Developer-299 submitted a review, later dismissed

2024-02-28 13:59 UTC, jd239 requested changes
Just a single comment :)

2024-02-28 14:47 UTC, GCHQ-Developer-299 approved these changes

2024-02-29 11:00 UTC, jd239 requested changes
Quick formatting issues

2024-02-29 11:00 UTC, jd239 commented on src/content/structured/components/page-header/code.mdx
> +</ic-page-header>`,
So the indentation is still not quite right. I think line 491-499 needs to be outdented to remove the empty spaces.

2024-02-29 11:00 UTC, jd239 commented on src/content/structured/components/page-header/code.mdx
> +</ic-page-header>`,
Same with the React snippet:
![image](https://github.com/mi6/ic-design-system/assets/116016939/02f13dbc-5c74-47ef-b556-0ecf53572bc0)

2024-02-29 14:14 UTC, jd239 approved these changes

2024-02-29 14:19 UTC, GCHQ-Developer-299 approved these changes

2024-02-29 14:19 UTC, merged