docs(root): add accessible labels to chip icons
mi6/ic-design-system pull request #840
Opened 2024-02-28 09:24 UTC by GCHQ-Developer-299

## Summary of the changes

Update IcChip guidance and examples to have aria-labels 

## Related issue

#1560

## Checklist

- [ ] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [ ] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-02-28 09:40 UTC, GCHQ-Developer-530 approved these changes

2024-02-28 13:51 UTC, jd239 reviewed
Minor update to the code snippets

2024-02-28 13:51 UTC, jd239 commented on src/content/structured/components/chips/code.mdx
Could we improve the indentation in our code snippets? I appreciate it's not in this ticket but shouldn't take too long to complete.

2024-02-28 13:51 UTC, jd239 commented on src/content/structured/components/chips/code.mdx
Example of the tags not lining up correctly:

![image](https://github.com/mi6/ic-design-system/assets/116016939/5fd23e65-6cf5-4932-8989-0d4d73eeb9bf)

2024-02-28 14:48 UTC, GCHQ-Developer-530 approved these changes

2024-02-29 10:47 UTC, jd239 requested changes
Some very very minor updates

2024-02-29 10:47 UTC, jd239 commented on src/content/structured/components/chips/code.mdx
> +      <path d="M2,21H20V19H2M20,8H18V5H20M20,3H4V13A4,4 0 0,0 8,17H14A4,4 0 0,0 18,13V10H20A2,2 0 0,0 22,8V5C22,3.89 21.1,3 20,3Z"/>
This needs to be outdented a bit.

2024-02-29 10:47 UTC, jd239 commented on src/content/structured/components/chips/code.mdx
> +      <path d="M2,21H20V19H2M20,8H18V5H20M20,3H4V13A4,4 0 0,0 8,17H14A4,4 0 0,0 18,13V10H20A2,2 0 0,0 22,8V5C22,3.89 21.1,3 20,3Z"/>
Needs to be outdented a bit

2024-02-29 10:47 UTC, jd239 commented on src/content/structured/components/chips/code.mdx
> +      <path d="M2,21V19H20V21H2M20,8V5H18V8H20M20,3A2,2 0 0,1 22,5V8A2,2 0 0,1 20,10H18V13A4,4 0 0,1 14,17H8A4,4 0 0,1 4,13V3H20M16,5H6V13A2,2 0 0,0 8,15H14A2,2 0 0,0 16,13V5Z"/>
Needs to be outdented a btit. Same position as the React example below

2024-02-29 10:47 UTC, jd239 commented on src/content/structured/components/chips/code.mdx
> +      aria-label="coffee"
Line up with other attributes

2024-02-29 14:12 UTC, jd239 approved these changes

2024-02-29 14:51 UTC, zxh722 approved these changes

2024-02-29 14:54 UTC, merged