fix(root): add scroll margin to navigation headings
mi6/ic-design-system pull request #856
Opened 2024-03-18 14:20 UTC by GCHQ-Developer-530

## Summary of the changes

Add scroll margin to navigation headings to ensure heading doesn't hide behind the page header when anchor nav link is clicked

## Related issue

#728 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-03-18 14:55 UTC, gd2910 submitted a review, later dismissed

2024-03-18 15:21 UTC, GCHQ-Developer-299 approved these changes

2024-03-18 15:32 UTC, GCHQ-Developer-299 requested changes
The increased margin is interfering with the Table of Contents on pages, when you click to scroll to a heading, the table of contents will instead highlight the heading below

2024-03-19 08:58 UTC, GCHQ-Developer-299 approved these changes

2024-03-19 09:17 UTC, gd2910 approved these changes

2024-03-19 09:18 UTC, merged