763 side navigation layout guidance page
mi6/ic-design-system pull request #864
Opened 2024-03-20 09:50 UTC by GCHQ-Developer-112

## Summary of the changes

Tell us, in a few words, what the changes are.

## Related issue

Tell us the issue number. If suggesting an improvement or component, please discuss it with us in an issue first.

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-03-26 13:05 UTC, GCHQ-Developer-112 commented
[Branch deployment](https://animated-fiesta-gvyom1k.pages.github.io/branches/763-side-navigation-layout-guidance-page/patterns)

2024-04-02 14:17 UTC, gd2910 commented
I'm getting some  weird navigation-item heights when expanded
![image](https://github.com/mi6/ic-design-system/assets/122624946/1d78da37-ae24-4bee-a304-c61b4d89652c)
Fixed by getting rid of the calculated height, but ~annoyingly~ interestingly when in collapsed satte the nav-items have the same issue as above.
![image](https://github.com/mi6/ic-design-system/assets/122624946/66a72b30-db74-4874-be18-d94bb20715fd)

2024-04-03 14:26 UTC, GCHQ-Developer-847 requested changes
Looks amazing 😃 Noticed a few things but only very small

I can't view the StackBlitz examples at the moment because of the issues with builds loading properly (I think the StackBlitz buttons can only appear on the build and not locally?)

2024-04-05 17:13 UTC, GCHQ-Developer-112 commented
> Looks amazing 😃 Noticed a few things but only very small
> 
> I can't view the StackBlitz examples at the moment because of the issues with builds loading properly (I think the StackBlitz buttons can only appear on the build and not locally?)

Yes, on line 216, the showStackblitzBtn prop is dependent on whether the environment is prod or dev >> `showStackblitzBtn={!!process.env.GATSBY_GA_TRACKING_ID && type === "pattern"}`
 
 To see the Stackblitz button in your local environment, you'll need to remove `!!process.env.GATSBY_GA_TRACKING_ID && `  so the prop is `showStackblitzBtn={type === "pattern"}` instead

2024-04-05 17:15 UTC, GCHQ-Developer-112 commented on src/icds-pages-data.json
As there's some new guidance page changes, I committed the regenerated docs file. I'm not aware of a way to stop the dates from being changed whilst keeping the new guidance in the docs, without going through the docs and reverting each date changed

Does the date change have a big impact?

2024-04-05 17:18 UTC, GCHQ-Developer-112 commented on src/components/CodePreview/index.tsx
> +            size={isLargeViewport ? "small" : "default"}
No, this is the correct way round. At the moment, the default height of the icon button (32px) is not the same as the default height of the regular button (40px). To get to be the same height, I need to set the size of the regular button to `small`

2024-04-09 11:23 UTC, GCHQ-Developer-112 commented
> Just taking a look at the StackBlitz demo;
> 
> I'm getting some weird navigation-item heights when expanded ![image](https://private-user-images.githubusercontent.com/122624946/318813879-1d78da37-ae24-4bee-a304-c61b4d89652c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NjE5OTksIm5iZiI6MTcxMjY2MTY5OSwicGF0aCI6Ii8xMjI2MjQ5NDYvMzE4ODEzODc5LTFkNzhkYTM3LWFlMjQtNGJlZS1hMzA0LWM2MWI0ZDg5NjUyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxMTIxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDA0ZGY4NzA3ZmE4YmJkZDAzYjk4OTk4MjNmMTdhZmU0MjI1Mzc0OWFjY2VjMTI0MDRhYjFiYTQ3YmIxODYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vu3CG5Gj74vlDwXYmg0gBUcxRhtrHkKURHBXrLXTMjc) Fixed by getting rid of the calculated height, but ~annoyingly~ interestingly when in collapsed satte the nav-items have the same issue as above. ![image](https://private-user-images.githubusercontent.com/122624946/318813257-66a72b30-db74-4874-be18-d94bb20715fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NjE5OTksIm5iZiI6MTcxMjY2MTY5OSwicGF0aCI6Ii8xMjI2MjQ5NDYvMzE4ODEzMjU3LTY2YTcyYjMwLWRiNzQtNDg3NC1iZTE4LWQ5NGJiMjA3MTVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxMTIxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NWIzM2NkZjc4NjExNjQ3NWE0MzY2ZTEyNjkzZWIwOTM4N2YzNzQzM2M0Y2ExNTIyYjMxMDM3MmJhNDc0YTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BHvyLpGGo68BLUBursydmVRYfCvyBxtgyXKaI0Z_ks0)

I've now created a PR to fix this issue: [Add auto height to `ic-navigation-item` when it's in the side menu to prevent it stretching when used in StackBlitz](https://github.com/mi6/ic-ui-kit/pull/1745)

2024-04-09 14:51 UTC, GCHQ-Developer-847 commented on src/icds-pages-data.json
Ahh sorry - I was thinking these dates corresponded to the "last reviewed" ones at the bottom of the page, ignore me! All good and makes sense 👍

2024-04-09 15:35 UTC, GCHQ-Developer-847 approved these changes

2024-04-16 15:10 UTC, merged