fix(root): add max width to component preview, and use attribute cards for xs breakpoint
mi6/ic-design-system pull request #90
Opened 2022-11-28 14:00 UTC by GCHQ-Developer-530

## Summary of the changes
Add max width to component preview, and use attribute cards for xs breakpoint

## Related issue
#86

## Checklist
- [x] I have manually accessibility tested any changes, if relevant.

2022-11-28 14:36 UTC, GCHQ-Developer-112 submitted a review, later dismissed

2022-11-28 17:40 UTC, GCHQ-Developer-465 requested changes

2022-11-28 17:40 UTC, GCHQ-Developer-465 commented on src/components/AttributeCards/index.css
> +  padding: 16px;
Correct me If I am wrong, I'm sure we can use a token here? 
```suggestion
  padding: var(--ic-space-md);
```

2022-11-29 09:07 UTC, GCHQ-Developer-112 approved these changes

2022-11-29 10:18 UTC, GCHQ-Developer-465 approved these changes

2022-11-29 10:46 UTC, merged