Feat/stackblitz component code examples
mi6/ic-design-system pull request #906
Opened 2024-04-12 14:35 UTC by GCHQ-Developer-112

## Summary of the changes
- update code examples to work with the new Stackblitz functionality
- add toggle button to switch between typescript and javascript
- add show more/less button to component code examples

## Related issue
#751 

## Checklist

- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-05-15 11:40 UTC, GCHQ-Developer-299 commented on src/content/structured/components/back-to-top/code.mdx
Back To Top's Stackblitz example doesn't really work by virtue of the code preview not being tall enough to scroll

Would this be a good instance to not display the stackblitz button?

2024-05-21 10:05 UTC, GCHQ-Developer-112 commented on src/content/structured/components/back-to-top/code.mdx
I have now removed the back to top stackblitz example and added a link to the Top Navigation with back to top pattern example instead

2024-06-03 08:25 UTC, GCHQ-Developer-299 commented on src/components/CodePreview/index.tsx
> +    // const findStyleIndex = (lines: string[]) =>
just a note to remove these commented-out lines before we merge this

2024-06-03 11:00 UTC, GCHQ-Developer-299 commented on src/content/structured/patterns/top-navigation-layout.mdx
> +    technology: "Web component",
![Screenshot 2024-06-03 at 11 59 56](https://github.com/mi6/ic-design-system/assets/111292477/8ad29f9a-a71b-4071-98a0-f16a47530188)

There's an error with the Web Components code-block here. (React Codeblock displays fine)

2024-06-03 11:01 UTC, GCHQ-Developer-299 commented on src/content/structured/patterns/top-navigation-layout.mdx
> +    technology: "Web component",
The Side navigation page has the same issue.

2024-06-04 11:01 UTC, jd239 requested changes
This is a great PR which will take the guidance component pages up a notch. I've added a few comments. Also, noticed that switching between TS and JS when the short code snippets were displayed didn't show any difference (must admit, I didn't check all the examples). Is it possible to only show the toggle when 'show full code' has been clicked?

2024-06-04 11:04 UTC, GCHQ-Developer-112 commented on src/content/structured/components/badge/code.mdx
> +  }
Yes, this is to do with Stackblitz. Where a component has a focus indicator, I've added a container div so that the focus indicator isn't cut off

2024-06-04 11:05 UTC, GCHQ-Developer-112 commented on src/content/structured/components/badge/code.mdx
> +<ComponentPreview snippets={snippetsSizes} style={{ gap: "16px" }}>
Does this apply to just the code being passed through the ComponentPreview or all code examples?

2024-06-04 11:08 UTC, GCHQ-Developer-112 commented on src/content/structured/components/accordion/code.mdx
> +    technology: "Web component",
I thought `language` applies better to the difference between TypeScript and JavaScript. Technically React and Web components aren't languages and thought `technology` was a better way to describe them

2024-06-05 11:09 UTC, GCHQ-Developer-465 commented
This is awesome work! 🌟

My only concern is the work for this [issue](https://github.com/mi6/ic-design-system/issues/938)

As you can see below...
![Screenshot 2024-06-05 at 11 57 10](https://github.com/mi6/ic-design-system/assets/111882114/6da7f1ce-ccc4-470f-abcd-d711edae16aa)

The code tabs are displayed inside the “code-actions” alongside the StackBlitz Button and Copy Code button. This would revert some of the changes, if not complicate this work. 

Happy to discuss internally more about this in detail @GCHQ-Developer-112, so that we can collaborate as these issues link together.

2024-06-05 11:20 UTC, GCHQ-Developer-465 commented
Also when clicking on either TypeScript or JavaScript again it deselects this and the toggle button is no longer 'filled', thus does not confirm to the user what language they are viewing. 

Please see my screenshots of this bug below:
<img width="848" alt="Screenshot 2024-06-05 at 12 14 07" src="https://github.com/mi6/ic-design-system/assets/111882114/cdc05ccb-6a8d-4d1b-8c26-81396fd1404f">
<img width="845" alt="Screenshot 2024-06-05 at 12 14 16" src="https://github.com/mi6/ic-design-system/assets/111882114/3fe24cb8-bbe4-4010-ad11-7367027d8e27">
<img width="840" alt="Screenshot 2024-06-05 at 12 14 24" src="https://github.com/mi6/ic-design-system/assets/111882114/bfa7725a-047e-4f87-bb90-043f042252d3">

I don't think this should be the case as the Toggle Button should always be either selected in the group, so that it is clear to the user. 

Not too sure if the TypeScript / JavaScript buttons are actually working as well...? 

Happy to discuss further if needed 😊

2024-06-13 12:21 UTC, GCHQ-Developer-299 commented on src/components/CodePreview/index.tsx
> +    // const findStyleIndex = (lines: string[]) =>
Still got these commented lines!

2024-06-13 12:22 UTC, GCHQ-Developer-299 approved these changes

2024-06-13 15:19 UTC, jd239 commented on src/content/structured/components/data-table/code.mdx
> +    actions: \`<ic-button variant='destructive' onClick='this.closest("tr").remove()'>Delete</ic-button>\`,
Is this still to be removed?

2024-06-13 15:23 UTC, jd239 commented on src/content/structured/components/badge/code.mdx
> +<ComponentPreview snippets={snippetsSizes} style={{ gap: "16px" }}>
I was just relating it to the component previews.

2024-06-13 16:02 UTC, jd239 approved these changes

2024-06-14 08:04 UTC, GCHQ-Developer-299 approved these changes

2024-06-14 08:05 UTC, merged