Add canary guidance to site
mi6/ic-design-system pull request #933
Opened 2024-05-01 14:28 UTC by GCHQ-Developer-741

## Summary of the changes
After making relevant changes to page structure, images and other content, the canary components can now be added to the guidance site. Have included them in the main list of components, with a status tag identifying them as canary compared to other components. Adjusted other page's navPriority to order them correctly in the left hand nav.

## Related issue
#929 

## Checklist
- [x] I have [manually accessibility tested](https://design.sis.gov.uk/accessibility/testing/manual-testing) any changes, if relevant.
- [x] I have raised this pull request against the [develop branch](https://github.com/mi6/ic-design-system/tree/develop)

2024-05-02 08:27 UTC, GCHQ-Developer-112 requested changes

2024-05-02 08:27 UTC, GCHQ-Developer-112 commented on src/content/structured/components/data-table/guidance.mdx
> +</p>
```suggestion
<p>
  Additional details on props and events for this component can be found in the ICDS{" "}
  <IcLink
    href="https://mi6.github.io/ic-ui-kit/branches/develop/canary-web-components/?path=/docs/web-components-data-table--docs"
    target="_blank"
  >Canary Web Components
 </IcLink>{" "}
  and{" "}
 <IcLink
    href="https://mi6.github.io/ic-ui-kit/branches/develop/canary-react/?path=/docs/react-components-data-table--docs"
    target="_blank"
  >Canary React
  </IcLink>{" "}
  Storybooks for this component.
</p>
```

2024-05-02 08:27 UTC, GCHQ-Developer-112 commented on src/content/structured/components/data-table/guidance.mdx
> +For more information on canary components read our approach to [releases and versions](/get-started/releases-versions).
```suggestion
For more information on canary components, read our approach to [releases and versions](/get-started/releases-versions).
```

2024-05-02 08:27 UTC, GCHQ-Developer-112 commented on src/content/structured/components/date-input/guidance.mdx
> +</p>
```suggestion
<p>
  Additional details on props and events for this component can be found in the ICDS{" "}
  <IcLink
    href="https://mi6.github.io/ic-ui-kit/branches/develop/canary-web-components/?path=/docs/web-components-date-input--docs"
    target="_blank"
  >Canary Web Components
 </IcLink>{" "}
  and{" "}
 <IcLink
    href="https://mi6.github.io/ic-ui-kit/branches/develop/canary-react/?path=/docs/react-components-date-input--docs"
    target="_blank"
  >Canary React
  </IcLink>{" "}
  Storybooks for this component.
</p>
```

2024-05-02 08:27 UTC, GCHQ-Developer-112 commented on src/content/structured/components/date-input/guidance.mdx
> +For more information on canary components read our approach to [releases and versions](/get-started/releases-versions).
```suggestion
For more information on canary components, read our approach to [releases and versions](/get-started/releases-versions).
```

2024-05-02 08:27 UTC, GCHQ-Developer-112 commented on src/content/structured/components/date-picker/guidance.mdx
> +</p>
```suggestion
<p>
  Additional details on props and events for this component can be found in the ICDS{" "}
  <IcLink
    href="https://mi6.github.io/ic-ui-kit/branches/develop/canary-web-components/?path=/docs/web-components-date-picker--docs"
    target="_blank"
  >Canary Web Components
 </IcLink>{" "}
  and{" "}
 <IcLink
    href="https://mi6.github.io/ic-ui-kit/branches/develop/canary-react/?path=/docs/react-components-date-picker--docs"
    target="_blank"
  >Canary React
  </IcLink>{" "}
  Storybooks for this component.
</p>
```

2024-05-02 08:27 UTC, GCHQ-Developer-112 commented on src/content/structured/components/date-picker/guidance.mdx
> +For more information on canary components read our approach to [releases and versions](/get-started/releases-versions).
```suggestion
For more information on canary components, read our approach to [releases and versions](/get-started/releases-versions).
```

2024-05-02 12:42 UTC, GCHQ-Developer-112 requested changes
Sorry, more edits - re-read the sentences and realised they could be clearer

2024-05-07 15:18 UTC, GCHQ-Developer-112 approved these changes

2024-05-08 07:35 UTC, GCHQ-Developer-530 commented on src/content/structured/components/date-picker/guidance.mdx
> +    state="good"
This looks like there's a good state overlapping another good state. Might be worth removing the good state from the original image.
<img width="408" alt="Screenshot 2024-05-08 at 08 33 46" src="https://github.com/mi6/ic-design-system/assets/111882034/77011e5c-b002-43de-93a3-db225a28e0f7">

2024-05-09 06:38 UTC, GCHQ-Developer-530 approved these changes

2024-05-09 10:01 UTC, GCHQ-Developer-465 reviewed
Is there a need to squash the commits? It may be worth considering having 1 commit for this to sum up the canary guidance.

2024-05-09 13:39 UTC, GCHQ-Developer-465 approved these changes

2024-05-09 14:00 UTC, GCHQ-Developer-530 approved these changes

2024-05-09 14:16 UTC, merged